version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - ./db-data:/data/db
    ports:
      - 27017:27017
    env_file:
      - ./env/.env.mongo

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    restart: always

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - /app/node_modules
    env_file:
      - ./env/.env.server
    depends_on:
      - mongodb
      - redis

volumes:
  redis_data:
